import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

async function login(page: Page) {
  await page.goto('/')
  await page.getByLabel('소유자 키', { exact: true }).fill('browser-test-owner-key')
  await page.getByRole('button', { name: '작업 공간 열기' }).click()
  await page.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  await expect(page.getByLabel('요약', { exact: true })).toBeVisible()
}

test('근거 탐색, 편집 충돌, 확정 버전 보존, 전사 수정/되돌리기', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await login(page)
  const other = await context.newPage()
  await other.goto('/')
  await other.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  await expect(other.getByLabel('요약', { exact: true })).toBeVisible()
  await page.locator('.evidence').first().getByRole('button', { name: '0:02 ·' }).click()
  await expect(page.locator('#segment-s2')).toHaveClass(/focused/)
  await expect.poll(() => page.locator('audio').evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBe(2)
  await page.getByLabel('요약', { exact: true }).fill('수정한 한글 요약 <script>window.pwned=1</script>')
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '설정 및 진단', exact: false }).click()
  await expect(page.getByLabel('요약', { exact: true })).toHaveValue('수정한 한글 요약 <script>window.pwned=1</script>')
  await page.getByLabel('검토 상태', { exact: true }).nth(0).selectOption('verified')
  await page.getByLabel('검토 상태', { exact: true }).nth(1).selectOption('verified')
  await page.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(page.getByText('새 회의록 초안을 저장했습니다.', { exact: true })).toBeVisible()
  await other.getByLabel('요약', { exact: true }).fill('다른 탭의 입력은 보존')
  await other.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(other.getByRole('alert')).toContainText('다른 탭')
  await expect(other.getByLabel('요약', { exact: true })).toHaveValue('다른 탭의 입력은 보존')
  await other.close()
  await page.getByRole('button', { name: '검토한 회의록 확정', exact: true }).click()
  await expect(page.getByText('확정 버전을 저장했습니다.', { exact: true })).toBeVisible()
  const confirmed = await page.getByLabel('회의록 버전', { exact: true }).inputValue()
  await page.getByLabel('요약', { exact: true }).fill('확정 후 새 초안')
  await page.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(page.getByText('새 회의록 초안을 저장했습니다.', { exact: true })).toBeVisible()
  await page.getByLabel('회의록 버전', { exact: true }).selectOption(confirmed)
  await expect(page.getByLabel('요약', { exact: true })).toHaveValue('수정한 한글 요약 <script>window.pwned=1</script>')
  await expect(page.getByLabel('요약', { exact: true })).toBeDisabled()
  await page.getByText('저장된 회의록의 근거 보기', { exact: true }).click()
  await page.locator('.readonly-evidence').getByRole('button').first().click()
  await expect(page.locator('#segment-s2')).toHaveClass(/focused/)
  await page.getByRole('button', { name: '최신 내용 불러오기', exact: true }).click()
  await page.getByLabel('발언 내용', { exact: true }).first().fill('수정된 발언')
  await page.getByRole('button', { name: '발언 저장', exact: true }).first().click()
  await expect(page.getByText('새 전사 버전을 저장했습니다. 원본은 보존됩니다.', { exact: true })).toBeVisible()
  await expect(page.getByText('이 회의록은 이전 전사를', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '이전 수정 되돌리기', exact: true }).click()
  await expect(page.getByLabel('발언 내용', { exact: true }).first()).toHaveValue('금요일 배포를 제안합니다.')
  await page.getByLabel('화자 이름', { exact: true }).first().fill('진행자')
  await page.getByRole('button', { name: '이름 저장', exact: true }).first().click()
  await expect(page.getByLabel('화자 이름', { exact: true }).first()).toHaveValue('진행자')
  await page.getByText('화자 병합 · 후보 확인', { exact: true }).click()
  await page.getByLabel('합칠 화자', { exact: true }).selectOption('B')
  await page.getByLabel('남길 화자', { exact: true }).selectOption('A')
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '화자 병합', exact: true }).click()
  await expect(page.getByLabel('화자 이름', { exact: true })).toHaveCount(1)
  await page.getByRole('button', { name: '이전 수정 되돌리기', exact: true }).click()
  await expect(page.getByLabel('화자 이름', { exact: true })).toHaveCount(2)
  await page.getByLabel('현재 전사 텍스트의 Codex 전송 허용', { exact: true }).check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '새 초안 생성', exact: true }).click()
  await expect(page.getByText('생성 작업을 대기열에 등록했습니다. 완료 후 최신 내용을 불러오세요.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.hasOwn(window, 'pwned'))).toBe(false)
  await page.screenshot({ path: '../../.workflow/evidence/g5-detail.png', fullPage: true })
  expect(errors).toEqual([])
})

test('키보드 로그인과 실제 파일 업로드, 검색, 대기 작업 취소', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('소유자 키', { exact: true }).fill('browser-test-owner-key')
  await page.getByLabel('소유자 키', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
  await page.getByLabel('회의 제목', { exact: true }).fill('업로드 확인 회의')
  const wav = Buffer.alloc(44 + 32000)
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16)
  wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(16000, 24); wav.writeUInt32LE(32000, 28)
  wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(32000, 40)
  const transfer = await page.evaluateHandle(bytes => {
    const value = new DataTransfer()
    value.items.add(new File([new Uint8Array(bytes)], '회의 음성.wav', { type: 'audio/wav' }))
    return value
  }, Array.from(wav))
  await page.locator('.upload-form').dispatchEvent('drop', { dataTransfer: transfer })
  await transfer.dispose()
  await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
  const row = page.locator('.meeting-row').filter({ hasText: '업로드 확인 회의' })
  await expect(row).toContainText('대기', { timeout: 10000 })
  await row.getByRole('button', { name: '취소', exact: true }).click()
  await expect(row).toContainText('취소됨')
  await page.getByLabel('제목·본문 검색', { exact: true }).fill('업로드 확인')
  await expect(page.locator('.meeting-row')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('자동 보관 기본값과 저장, 확인 후 회의 삭제', async ({ page }) => {
  await login(page)
  await page.getByRole('button', { name: '설정 및 진단', exact: false }).click()
  await expect(page.getByRole('heading', { name: '런타임 Codex', exact: true })).toBeVisible()
  await expect(page.getByText('계정 전체 남은 한도', { exact: true })).toBeVisible()
  await expect(page.getByLabel('자동 삭제 사용', { exact: true })).not.toBeChecked()
  await page.getByLabel('원본 음성·영상 보관 일수', { exact: true }).fill('30')
  await page.getByLabel('재생용 추출 음성 보관 일수', { exact: true }).fill('60')
  await page.getByLabel('자동 삭제 사용', { exact: true }).check()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '보관 정책 저장', exact: true }).click()
  await expect(page.getByText('보관 정책을 저장했습니다.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '내 회의', exact: false }).first().click()
  await page.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  page.once('dialog', dialog => dialog.dismiss())
  await page.getByRole('button', { name: '회의 전체 삭제', exact: true }).click()
  await expect(page.getByRole('button', { name: '브라우저 검증 회의', exact: true })).toBeVisible()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: '회의 전체 삭제', exact: true }).click()
  await expect(page.getByText('회의 자료 삭제가 완료됐습니다.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '브라우저 검증 회의', exact: true })).toHaveCount(0)
})

test('실제 MP4 브라우저 업로드와 잘못된 파일 오류', async ({ page }) => {
  const directory = mkdtempSync(join(tmpdir(), 'minutes-video-'))
  try {
    const path = join(directory, '영상 회의.mp4')
    execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=c=black:s=32x32:d=1',
      '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', '-c:v', 'mpeg4', '-c:a', 'aac', '-shortest', path])
    await page.goto('/')
    await page.getByLabel('소유자 키', { exact: true }).fill('browser-test-owner-key')
    await page.getByLabel('소유자 키', { exact: true }).press('Enter')
    await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
    await page.getByLabel('회의 제목', { exact: true }).fill('영상 업로드 확인')
    await page.getByLabel('음성 또는 영상 파일', { exact: true }).setInputFiles(path)
    await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
    await expect(page.locator('.meeting-row').filter({ hasText: '영상 업로드 확인' })).toContainText('대기', { timeout: 10000 })
    await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
    await page.getByLabel('회의 제목', { exact: true }).fill('거부할 파일')
    await page.getByLabel('음성 또는 영상 파일', { exact: true }).setInputFiles({ name: 'unsupported.exe', mimeType: 'application/octet-stream', buffer: Buffer.from('not media') })
    await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('지원하는 미디어 파일')
  } finally { rmSync(directory, { recursive: true, force: true }) }
})
