import { test, expect } from '@playwright/test'
import type { Page } from '@playwright/test'
import { execFileSync } from 'node:child_process'
import { mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

async function openMeeting(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  await expect(page.getByRole('button', { name: '회의록 편집', exact: true })).toBeVisible()
}

test('논제 읽기·시각 이동, 편집 충돌, 저장 버전 보존, 간결한 결과 UI', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await openMeeting(page)
  await expect(page.getByLabel('요약', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('화자 이름')).toHaveCount(0)
  await expect(page.getByLabel('검토 상태')).toHaveCount(0)
  await page.getByRole('button', { name: '회의록 편집', exact: true }).click()
  const other = await context.newPage()
  await other.goto('/')
  await other.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  await other.getByRole('button', { name: '회의록 편집', exact: true }).click()
  await page.getByLabel('요약', { exact: true }).fill('수정한 한글 요약 <script>window.pwned=1</script>')
  await page.getByRole('button', { name: '00:02 논의 시작', exact: true }).click()
  await expect.poll(() => page.locator('audio').evaluate((audio: HTMLAudioElement) => audio.currentTime)).toBeGreaterThanOrEqual(2)
  await expect(page.getByLabel('요약', { exact: true })).toHaveValue('수정한 한글 요약 <script>window.pwned=1</script>')
  await page.getByRole('button', { name: '설정 및 진단', exact: false }).click()
  await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.getByLabel('요약', { exact: true })).toBeVisible()
  await page.getByLabel('담당자', { exact: true }).fill('운영팀')
  await page.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(page.getByText('새 회의록 초안을 저장했습니다.', { exact: true })).toBeVisible()
  await other.getByLabel('요약', { exact: true }).fill('다른 탭의 입력은 보존')
  await other.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(other.getByRole('alert')).toContainText('다른 탭')
  await expect(other.getByLabel('요약', { exact: true })).toHaveValue('다른 탭의 입력은 보존')
  await other.close()
  await expect(page.getByRole('button', { name: '회의록 확정', exact: true })).toHaveCount(0)
  const saved = await page.getByLabel('회의록 버전', { exact: true }).inputValue()
  await page.getByRole('button', { name: '회의록 편집', exact: true }).click()
  await page.getByLabel('요약', { exact: true }).fill('다음 수정본')
  await page.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(page.getByText('새 회의록 초안을 저장했습니다.', { exact: true })).toBeVisible()
  await page.getByLabel('회의록 버전', { exact: true }).selectOption(saved)
  await expect(page.getByRole('link', { name: '텍스트 내보내기', exact: true })).toHaveAttribute('href', new RegExp(`version=${saved}$`))
  await expect(page.getByRole('link', { name: 'Markdown 내보내기', exact: true })).toHaveAttribute('href', new RegExp(`version=${saved}$`))
  await expect(page.getByText('수정한 한글 요약 <script>window.pwned=1</script>', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '회의록 편집', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '최신 내용 불러오기', exact: true }).click()
  await expect(page.getByText('전사문', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '이 버전 Markdown', exact: true })).toHaveCount(0)
  await expect(page.getByRole('link', { name: '이 버전 텍스트', exact: true })).toHaveCount(0)
  const regenerate = page.getByRole('button', { name: '초안 재생성', exact: true })
  await regenerate.click()
  const modal = page.getByRole('dialog')
  await expect(modal.getByRole('button', { name: '취소', exact: true })).toBeFocused()
  for (const key of ['Tab', 'Tab', 'Shift+Tab', 'Shift+Tab']) {
    await page.keyboard.press(key)
    expect(await modal.evaluate(node => node.contains(document.activeElement))).toBe(true)
  }
  await modal.getByRole('button', { name: '취소', exact: true }).click()
  await expect(regenerate).toBeFocused()
  await regenerate.click()
  await page.keyboard.press('Escape')
  await expect(regenerate).toBeFocused()
  await regenerate.click()
  await page.getByRole('dialog').getByRole('button', { name: '확인', exact: true }).click()
  await expect(page.getByText('AI 요약 작업을 등록했습니다. 완료되면 새 버전을 표시합니다.', { exact: true })).toBeVisible()
  expect(await page.evaluate(() => Object.hasOwn(window, 'pwned'))).toBe(false)
  await page.screenshot({ path: '../../.workflow/evidence/m2/detail.png', fullPage: true })
  expect(errors).toEqual([])
})

test('원문 만료 결과의 독립 열람·시간 표시·편집·저장', async ({ page }) => {
  await openMeeting(page)
  await page.getByRole('button', { name: '원문 만료 회의', exact: true }).click()
  await expect(page.getByText('원문 없이 보존된 회의록', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '01:00:01 논의 시작', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '초안 재생성', exact: true })).toBeDisabled()
  await page.getByRole('button', { name: '회의록 편집', exact: true }).click()
  await page.getByLabel('요약', { exact: true }).fill('원문 만료 후에도 편집 성공')
  await page.getByRole('button', { name: '결정 직접 추가', exact: true }).click()
  await page.getByLabel('결정 내용', { exact: true }).fill('사용자가 추가한 결정')
  await page.getByRole('button', { name: '수정본 저장', exact: true }).click()
  await expect(page.getByText('새 회의록 초안을 저장했습니다.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '회의록 확정', exact: true })).toHaveCount(0)
  await expect(page.getByText('사용자가 추가한 결정', { exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../../.workflow/evidence/m2/expired-detail.png', fullPage: true })
})

test('키 없는 파일 업로드, 검색, 대기 작업 취소', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
  await page.getByLabel('회의 제목', { exact: true }).fill('업로드 확인 회의')
  const wav = Buffer.alloc(44 + 32000)
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16)
  wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(16000, 24); wav.writeUInt32LE(32000, 28)
  wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(32000, 40)
  const transfer = await page.evaluateHandle(bytes => {
    const value = new DataTransfer()
    value.items.add(new File([new Uint8Array(bytes)], '회의 음성.wav', { type: 'audio/wav' }))
    return value
  }, Array.from(wav))
  await page.locator('.upload-form').dispatchEvent('drop', { dataTransfer: transfer })
  await transfer.dispose()
  await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
  const row = page.locator('.meeting-row').filter({ hasText: '업로드 확인 회의' })
  await expect(row).toContainText('대기', { timeout: 10000 })
  await row.getByRole('button', { name: '취소', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
  await expect(row).toContainText('대기')
  await row.getByRole('button', { name: '취소', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '확인', exact: true }).click()
  await expect(row).toContainText('취소됨')
  await page.getByLabel('제목·본문 검색', { exact: true }).fill('업로드 확인')
  await expect(page.locator('.meeting-row')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('자동 보관 기본값과 저장, 확인 후 회의 삭제', async ({ page }) => {
  await openMeeting(page)
  await page.getByRole('button', { name: '설정 및 진단', exact: false }).click()
  await page.getByLabel('소유자 키', { exact: true }).fill('browser-test-owner-key')
  await page.getByRole('button', { name: '설정 열기', exact: true }).click()
  await expect(page.getByRole('heading', { name: '런타임 Codex', exact: true })).toBeVisible()
  await expect(page.getByText('계정 전체 남은 한도', { exact: true })).toBeVisible()
  await expect(page.getByLabel('자동 삭제 사용', { exact: true })).toBeChecked()
  await page.getByLabel('원본·재생용 음성·영상 보관 일수', { exact: true }).fill('30')
  await page.getByLabel('전사·정렬·화자 임베딩 보관 일수', { exact: true }).fill('60')
  await page.getByLabel('자동 삭제 사용', { exact: true }).check()
  await page.getByRole('button', { name: '보관 정책 저장', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '확인', exact: true }).click()
  await expect(page.getByText('보관 정책을 저장했습니다.', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '회의록', exact: false }).first().click()
  await page.getByRole('button', { name: '브라우저 검증 회의', exact: true }).click()
  await page.getByRole('button', { name: '회의 전체 삭제', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.getByRole('button', { name: '브라우저 검증 회의', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '회의 전체 삭제', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '확인', exact: true }).click()
  await expect(page.getByText('회의 자료 삭제가 완료됐습니다.', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '브라우저 검증 회의', exact: true })).toHaveCount(0)
})

test('실제 MP4 브라우저 업로드와 잘못된 파일 오류', async ({ page }) => {
  const directory = mkdtempSync(join(tmpdir(), 'minutes-video-'))
  try {
    const path = join(directory, '영상 회의.mp4')
    execFileSync('ffmpeg', ['-v', 'error', '-f', 'lavfi', '-i', 'color=c=black:s=32x32:d=1',
      '-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', '-c:v', 'mpeg4', '-c:a', 'aac', '-shortest', path])
    await page.goto('/')
        await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
    await page.getByLabel('회의 제목', { exact: true }).fill('영상 업로드 확인')
    await page.getByLabel('음성 또는 영상 파일', { exact: true }).setInputFiles(path)
    await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
    await expect(page.locator('.meeting-row').filter({ hasText: '영상 업로드 확인' })).toContainText('대기', { timeout: 10000 })
    await page.getByRole('button', { name: '새 회의 업로드', exact: true }).click()
    await page.getByLabel('회의 제목', { exact: true }).fill('거부할 파일')
    await page.getByLabel('음성 또는 영상 파일', { exact: true }).setInputFiles({ name: 'unsupported.exe', mimeType: 'application/octet-stream', buffer: Buffer.from('not media') })
    await page.getByRole('button', { name: '업로드하고 처리 시작', exact: true }).click()
    await expect(page.getByRole('alert')).toContainText('지원하는 미디어 파일')
  } finally { rmSync(directory, { recursive: true, force: true }) }
})
